enableInlineBuilds: true

enableInlineHunks: true

nodeLinker: node-modules

npmRegistryServer: '${REGISTRY_URL:-https://registry.npmjs.org}'

unsafeHttpWhitelist:
  - '*.taobao.org'

yarnPath: .yarn/releases/yarn-2.4.2.cjs
